import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav>
          <ul className="nav">
            <li className="nav__li"><Link href="/">Home</Link></li>
            <li className="nav__li"><Link href="/ssr">SSR</Link></li>
            <li className="nav__li"><Link href="/ssg">SSG</Link></li>
            <li className="nav__li"><Link href="/isr">ISR</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
